### ISSUE TITLE
Use the standard leaflet URL pattern of `#z/lat/lng` for the URL

### ISSUE THREAD

**Issue by tordans** [konturio/disaster-ninja-fe#133]
The way leaflet hash and openstreetmap stores the map position and zoom is `#z/lat/lng`.
Disaster ninja does not follow this pattern but instead uses `#z/lng/lat`.
That means, I cannot easily copy a location from another map provider to choose/change the location in map ninja.

* https://github.com/konturio/disaster-ninja-fe/blob/bc2c73c33afebef9ead3ac8acd710c61ee5b85cc/src/features/osm_edit_link/index.tsx#L22 shows the format the OSM website uses
* https://github.com/mlevans/leaflet-hash/blob/master/leaflet-hash.js#L43-L45 shows the same format for the common leaflet hash plugin

And it looks like https://github.com/konturio/disaster-ninja-fe/blob/main/src/core/url_store/atoms/urlStore.ts#L141-L143 is the place where disaster ninja sets and reads the map state in the URL.

**Comment by Akiyamka** [comment]
Nice catch!

**Comment by vkozio** [comment]
Thanks a lot, @tordans 
Implemented in https://github.com/konturio/disaster-ninja-fe/pull/261
